	const_def $01
	const AIRESPONSE_PLAY_INITIAL_POKEMON  ; $01
	const AIRESPONSE_PLAY_TRAINER          ; $02
	const AIRESPONSE_ATTACH_ENERGY         ; $03
	const AIRESPONSE_PLAY_POKEMON          ; $04
	const AIRESPONSE_FINISH_TURN_WO_ATK    ; $05
	const AIRESPONSE_TRY_ATTACK            ; $06
	const AIRESPONSE_AFTER_ATTACK          ; $07
	const AIRESPONSE_BETWEEN_TURNS         ; $08
	const AIRESPONSE_NEXT_TURN             ; $09
	const AIRESPONSE_START_TURN            ; $0a
	const AIRESPONSE_EVOLVE_POKEMON        ; $0b
	const AIRESPONSE_SHOW_TRAINER          ; $0c
	const AIRESPONSE_PICK_PRIZES           ; $0d
	const AIRESPONSE_TAKE_PRIZES           ; $0e
	const AIRESPONSE_KO_SWITCH             ; $0f
	const AIRESPONSE_ATTEMPT_RETREAT       ; $10
	const AIRESPONSE_HEAL_PARALYSIS        ; $11
	const AIRESPONSE_POISON_DAMAGE         ; $12
	const AIRESPONSE_PLAYER_SLEEP_CHECK    ; $13
	const AIRESPONSE_AI_SLEEP_CHECK        ; $14
	const AIRESPONSE_HEAL_SLEEP            ; $15
	const AIRESPONSE_PKMN_POWER_TEXT       ; $16
	const AIRESPONSE_UNABLE_USE_PKMN_POWER ; $17
	const AIRESPONSE_WILL_USE_PKMN_POWER   ; $18
	const AIRESPONSE_SMOKESCREEN_CHECK     ; $19
	const AIRESPONSE_SMOKESCREEN_TAILS     ; $1a
	const AIRESPONSE_CONFUSION_CHECK       ; $1b
	const AIRESPONSE_TRAINER_COIN_CHECK    ; $1c
	const AIRESPONSE_NO_MORE_BENCH         ; $1d
	const AIRESPONSE_TOOK_ALL_PRIZES       ; $1e
	const AIRESPONSE_DECISION              ; $1f
	const AIRESPONSE_CNF_RETREAT_CHECK     ; $20
	const AIRESPONSE_USE_PKMN_PWR          ; $21

	; PKMN powers
	const_def $40
	const AIRESPONSE_FIREGIVER             ; $40
	const AIRESPONSE_STRIKES_BACK          ; $41
	const AIRESPONSE_TRANSPARENCY_CHECK    ; $42

	; attacks
	const_def $80
	const AIRESPONSE_USED_ATTACK_TEXT     ; $80
	const AIRESPONSE_PREATK_COIN_TOSS     ; $81
	const AIRESPONSE_PREATK_N_COIN_TOSSES ; $82
	const AIRESPONSE_FETCH                ; $83
	const AIRESPONSE_DISCARD_1_FIRE       ; $84
	const AIRESPONSE_DISCARD_2_ENERGY     ; $85
	const AIRESPONSE_MIX_UP               ; $86
	const AIRESPONSE_PAY_DAY              ; $87
	const AIRESPONSE_MORPH                ; $88
	const AIRESPONSE_BENCH_SELECT         ; $89
	const AIRESPONSE_SHOW_AMNESIA_ATTACK  ;

	const_def $1
	const PKMNPWR_CURSE ; $1
